version: '3.8'

services:
  db_test:
    image: postgres:16
    environment:
      POSTGRES_DB: secre_db_test
      POSTGRES_USER: secre
      POSTGRES_PASSWORD: secre
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U secre -d secre_db_test"]
      interval: 5s
      timeout: 5s
      retries: 5

  api_test:
    build: .
    environment:
      - DATABASE_URL=postgresql://secre:secre@db_test:5432/secre_db_test
      - ENVIRONMENT=test
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    depends_on:
      db_test:
        condition: service_healthy
    command: pytest tests/ -v
